addSbtPlugin("org.scalameta"             % "sbt-scalafmt" % "2.3.0")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix" % "0.9.11")
addSbtPlugin("com.dwijnand"              % "sbt-dynver"   % "4.0.0")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype" % "3.8.1")
addSbtPlugin("com.jsuereth"              % "sbt-pgp"      % "2.0.0")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"  % "0.5.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.10")
